version: '3'

services:
  webserver:
    image: 'nginx:latest'
    container_name: 'webserver'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./html:/usr/share/nginx/html
